'use strict';
// ДАННЫЕ КЛУБА: редактируйте контакты, залы и цены здесь.
const CLUB = {phone:'+7 705 654 32 66',whatsapp:'77056543266',instagram:'https://www.instagram.com/mvp.gameclub/',map:'https://2gis.kz/semey/geo/70000001113628066',address:'г. Семей, улица Кайыма Мухамедханова, 36Б, ТД Vikar'};
const PACKAGES = [{id:'hour',name:'1 час',hours:1},{id:'three',name:'2+1 — 3 часа',hours:3},{id:'five',name:'3+2 — 5 часов',hours:5},{id:'day',name:'День',hours:8,start:'09:00',note:'09:00–17:00'},{id:'night',name:'Ночь',hours:12,start:'21:00',note:'21:00–09:00 следующего дня'}];
const ROOMS = [
{id:'standard',name:'Standard',from:1,to:25,cpu:'Intel Core i5-14400F',gpu:'NVIDIA GeForce RTX 5060',ram:'32 GB',monitor:'MSI MAG, 300 Гц',hz:300,headset:'HyperX Cloud 2',keyboard:'HyperX Alloy',mouse:'HyperX Haste',prices:[900,1800,2700,2500,3000],description:'Твой привычный ритм игры.'},
{id:'vip',name:'VIP',from:26,to:35,cpu:'Intel Core i5-14600K',gpu:'NVIDIA GeForce RTX 5060',ram:'32 GB',monitor:'AOC, 420 Гц',hz:420,headset:'HyperX Cloud 3',keyboard:'Logitech G Pro',mouse:'Logitech Superlight 1',prices:[1400,2800,4200,3000,3500],description:'Больше герц. Больше погружения.'},
{id:'bootcamp',name:'Bootcamp',from:36,to:40,cpu:'Intel Core i5-14600K',gpu:'NVIDIA GeForce RTX 5070',ram:'32 GB',monitor:'ROG Swift, 560 Гц',hz:560,headset:'Logitech G Pro X',keyboard:'Logitech G Pro',mouse:'Logitech Superlight 2',prices:[2000,4000,6000,5000,6000],description:'Пять мест. Одна команда.'}
];
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₸';
$('#year').textContent=new Date().getFullYear();
document.querySelectorAll('[data-address]').forEach(e=>e.textContent=CLUB.address);
document.querySelectorAll('[data-contact]').forEach(e=>{const k=e.dataset.contact;e.href=k==='phone'?'tel:+'+CLUB.whatsapp:k==='whatsapp'?'https://wa.me/'+CLUB.whatsapp:CLUB[k];if(k==='phone')e.textContent=CLUB.phone;});
$('#room-cards').innerHTML=ROOMS.map(r=>`<article class="room-card ${r.id}"><div class="picture"><img class="room-photo" src="assets/images/${r.id}.webp" alt="Монитор в зале ${r.name}" loading="lazy" width="440" height="260"><span class="room-number">ПК ${r.from}–${r.to}</span></div><div class="room-body"><div class="room-head"><h3>${r.name.toUpperCase()}</h3><span class="hz">${r.hz} Гц</span></div><p class="room-description">${r.description}</p><div class="spec-short"><span>${r.gpu.replace('NVIDIA GeForce ','')}</span><span>32 GB RAM</span></div><div class="room-cost"><div><strong>${money(r.prices[0])}</strong><small> / час</small></div><button class="details-button" data-info="${r.id}">Подробнее ↗</button></div><button class="button" data-book="${r.id}">Выбрать ${r.name} ↗</button></div></article>`).join('');
$('#price-table').innerHTML=`<div class="price-wrap"><table class="prices"><caption class="sr-only">Тарифы за одно игровое место. Нажмите цену для заявки.</caption><thead><tr><th scope="col">Пакет</th>${ROOMS.map(r=>`<th scope="col">${r.name}</th>`).join('')}</tr></thead><tbody>${PACKAGES.map((p,i)=>`<tr><th scope="row">${p.name}<small>${p.note||'Любое время'}</small></th>${ROOMS.map(r=>`<td><button class="price-book" data-book="${r.id}" data-package="${p.id}" aria-label="${r.name}, ${p.name}, ${money(r.prices[i])}">${money(r.prices[i])}</button></td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
$('#gallery-grid').innerHTML=ROOMS.map(r=>`<button class="gallery-item" data-gallery="${r.id}" aria-label="Увеличить фото ${r.name}"><img src="assets/images/${r.id}.webp" alt="Игровое место ${r.name}" width="440" height="260" loading="lazy"><span>${r.name.toUpperCase()} <b>↗</b></span></button>`).join('');
const menu=$('.menu-toggle'),nav=$('#nav');function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Открыть меню');}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';nav.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню');});
nav.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus();}});
let opener=null,scrollY=0;
function openDialog(d,trigger){closeMenu();opener=trigger||document.activeElement;if(document.body.style.position!=='fixed')scrollY=window.scrollY;document.body.style.position='fixed';document.body.style.top=`-${scrollY}px`;document.body.style.width='100%';d.showModal();d.scrollTop=0;}
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target.closest('[data-close]'))d.close();if(e.target===d){const b=d.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)d.close();}});d.addEventListener('close',()=>{if(document.querySelector('dialog[open]'))return;document.body.style.position='';document.body.style.top='';document.body.style.width='';window.scrollTo({top:scrollY,behavior:'instant'});if(opener?.isConnected)opener.focus({preventScroll:true});});d.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const list=[...d.querySelectorAll('button,a[href],input,select,textarea')].filter(x=>!x.disabled&&!x.hidden&&x.getClientRects().length);const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});});
const form=$('#booking-form'),f=form.elements;
$('#room-select').innerHTML=ROOMS.map(r=>`<option value="${r.id}">${r.name}</option>`).join('');
$('#package-select').innerHTML=PACKAGES.map(p=>`<option value="${p.id}">${p.name}${p.note?' · '+p.note:''}</option>`).join('');
const dateISO=d=>new Date(d.getTime()+5*3600000).toISOString().slice(0,10);
const humanDate=d=>new Intl.DateTimeFormat('ru-RU',{timeZone:'Asia/Almaty',day:'2-digit',month:'2-digit',year:'numeric'}).format(d);
const humanTime=d=>new Intl.DateTimeFormat('ru-RU',{timeZone:'Asia/Almaty',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d);
function room(){return ROOMS.find(r=>r.id===f.room.value);}function pack(){return PACKAGES.find(p=>p.id===f.package.value);}
function refreshPC(){const r=room();f.pc.innerHTML='<option value="">Без предпочтений</option>'+Array.from({length:r.to-r.from+1},(_,i)=>`<option value="${r.from+i}">ПК №${r.from+i}</option>`).join('');}
let customTime='';
function updatePrice(){const p=pack();if(p.start){if(!f.time.disabled)customTime=f.time.value;f.time.value=p.start;f.time.disabled=true;}else{if(f.time.disabled)f.time.value=customTime;f.time.disabled=false;}
$('#estimate').textContent=money(room().prices[PACKAGES.indexOf(p)]);$('#interval').textContent=p.start?`Фиксированный интервал: ${p.note}. Дата выше — дата начала пакета.`:`Продолжительность: ${p.hours} ${p.hours===1?'час':p.hours===3?'часа':'часов'}.`;}
f.room.addEventListener('change',()=>{refreshPC();updatePrice();});f.package.addEventListener('change',updatePrice);
form.addEventListener('input',()=>{$('#form-error').textContent='';$('#copy-status').textContent='';$('#copy-fallback').hidden=true;});
function showBooking(id,pkg,trigger){f.room.value=ROOMS.some(r=>r.id===id)?id:'standard';f.package.value=pkg||'hour';f.date.min=dateISO(new Date());refreshPC();updatePrice();$('#form-error').textContent='';openDialog($('#booking-dialog'),trigger);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-book]');if(b){showBooking(b.dataset.book,b.dataset.package,b);return;}const i=e.target.closest('[data-info]');if(i){const r=ROOMS.find(x=>x.id===i.dataset.info);$('#info-content').innerHTML=`<p class="eyebrow">ПК №${r.from}–${r.to}</p><h2 id="info-title">${r.name}</h2><p class="muted">${r.description}</p><dl class="spec-list">${[['Процессор',r.cpu],['Видеокарта',r.gpu],['Память',r.ram],['Монитор',r.monitor],['Наушники',r.headset],['Клавиатура',r.keyboard],['Мышь',r.mouse]].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><button class="button" id="info-book">Забронировать ${r.name} ↗</button>`;$('#info-book').onclick=()=>{$('#info-dialog').close();showBooking(r.id,'hour',i);};openDialog($('#info-dialog'),i);return;}const g=e.target.closest('[data-gallery]');if(g){const r=ROOMS.find(x=>x.id===g.dataset.gallery);$('#gallery-title').textContent=r.name+' / MVP Game Club';$('#gallery-image').src=`assets/images/${r.id}.webp`;$('#gallery-image').alt=`Фотография монитора в зале ${r.name}`;openDialog($('#gallery-dialog'),g);}});
function requestText(){f.name.setCustomValidity(f.name.value.trim()?'':'Введите имя.');const digits=f.phone.value.replace(/\D/g,'');f.phone.setCustomValidity(digits.length>=10&&digits.length<=15?'':'Введите телефон: от 10 до 15 цифр.');if(!form.reportValidity())return null;const r=room(),p=pack();const start=new Date(`${f.date.value}T${p.start||f.time.value}:00+05:00`);if(!Number.isFinite(start.getTime())||start.getTime()<=Date.now()){$('#form-error').textContent='Выберите будущую дату и время начала по времени Семей (UTC+5).';f.date.focus();return null;}if(f.pc.value&&(Number(f.pc.value)<r.from||Number(f.pc.value)>r.to)){$('#form-error').textContent='Выберите номер ПК в выбранном зале.';return null;}const end=new Date(start.getTime()+p.hours*3600000);return ['Здравствуйте! Хочу оставить заявку в MVP Game Club.','',`Имя: ${f.name.value.trim()}`,`Телефон: ${f.phone.value.trim()}`,`Зал: ${r.name}`,`Желаемый ПК: ${f.pc.value?'№'+f.pc.value:'без предпочтений'}`,`Начало: ${humanDate(start)}, ${humanTime(start)}`,`Окончание: ${humanDate(end)}, ${humanTime(end)}`,`Время: Семей (UTC+5)`,`Пакет: ${p.name}${p.note?' ('+p.note+')':''}`,`Предварительная стоимость: ${money(r.prices[PACKAGES.indexOf(p)])}`,`Комментарий: ${f.comment.value.trim()||'нет'}`,'','Прошу подтвердить наличие места и окончательные условия.'].join('\n');}
f.name.addEventListener('input',()=>f.name.setCustomValidity(''));f.phone.addEventListener('input',()=>f.phone.setCustomValidity(''));
form.addEventListener('submit',e=>{e.preventDefault();const text=requestText();if(!text)return;window.open(`https://wa.me/${CLUB.whatsapp}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer');$('#copy-status').textContent='Заявка подготовлена. Отправьте сообщение в WhatsApp. Если он не открылся, скопируйте текст кнопкой ниже.';});
$('#copy-request').addEventListener('click',async()=>{const text=requestText();if(!text)return;try{if(!navigator.clipboard)throw new Error('clipboard unavailable');await navigator.clipboard.writeText(text);$('#copy-status').textContent='Текст заявки скопирован. Вставьте его в WhatsApp и отправьте администратору.';}catch{const area=$('#copy-fallback');area.hidden=false;area.value=text;area.focus();area.select();$('#copy-status').textContent='Выделите и скопируйте текст ниже, затем отправьте в WhatsApp.';}});
refreshPC();updatePrice();
if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('reveal');io.unobserve(e.target);}}),{threshold:.06});document.querySelectorAll('.section-top,.room-card,.offer').forEach(e=>io.observe(e));}
